### ISSUE TITLE
Front end icons not displayed on my system

### ISSUE THREAD

**Issue by mirceasava** [Minds/front#28]
For several months now, my web browser experience has been significantly hindered by an improper rendering of the interface's icons, as you can very well see in the snapshots attached.
It becomes particularly difficult when I want to write comments which are longer than half a line.
I do not have this issue if I access Minds from a mobile's browser, only my desktop which runs an up-to-date Gentoo Linux. Is there a way for me to fix this?

![screenshot_20170514_200551](https://cloud.githubusercontent.com/assets/24976789/26036811/85f981ac-38e5-11e7-8815-91098610e072.png)
![screenshot_20170514_200614](https://cloud.githubusercontent.com/assets/24976789/26036814/85fc6d72-38e5-11e7-963d-4fb466b7487c.png)
![screenshot_20170514_200644](https://cloud.githubusercontent.com/assets/24976789/26036812/85fa43da-38e5-11e7-8a67-6334905afa81.png)
![screenshot_20170514_200714](https://cloud.githubusercontent.com/assets/24976789/26036813/85fa9b8c-38e5-11e7-8eab-8a03d31e284e.png)

**Comment by mirceasava** [comment]
In case I haven't made myself clear, I'm experiencing this with all browsers that I have at my disposal: Chromium, Aurora, Tor Browser, and Konqueror.

**Comment by ubuntume** [comment]
Did you install to a virtual machine and if so when? Installation at this point is fatal

**Comment by markharding** [comment]
Are you using any noscript or ad blockers?

**Comment by mirceasava** [comment]
Thanks for answering!

Indeed, I am using NoScript but that's a particular Aurora and Tor Browser use case. Anyhow, it is set to allow pretty much everything on the site.
For ad-blocking purposes I only use the system's hosts file -- that being said, I use an identical file on my phone but don't experience this issue accessing the site with the phone's browsers, and you guys don't have ads anyway.

Also, this behaviour didn't start from the beginning of my experience with the site but maybe a few months ago. I can't be sure, but this might've started around the same time I upgraded from ffmpeg2 to ffmpeg3 and rebuild all browsers but that shouldn't have affected the Tor Browser.

So yeah, it's a mystery.

**Comment by markharding** [comment]
Can you try whitelisting
https://fonts.googleapis.com/icon?family=Material+Icons ?

**Comment by mirceasava** [comment]
That did it, thanks!
Now, I have to remember why I blocked fonts.googleapis.com in the first place -- silly me forgot to put a comment next to it -- and then decide which compromise is more acceptable based on my threat model.
I'm already unhappy with the need for storage.googleapis.com, but unfortunately the site doesn't work without it.
But that's probably a discussion for another time and place.
Thanks again.

**Comment by ubuntume** [comment]
Sorry for such vast reply. I'm trying to ring just the source code on a
dedicated machine without vagrant. Where would details of packages for
environment.

On Jun 24, 2017 10:19 AM, "Mircea Sava" <notifications@github.com> wrote:

That did it, thanks!
Now, I have to remember why I blocked fonts.googleapis.com in the first
place -- silly me forgot to put a comment next to it -- and then decide
which compromise is more acceptable based on my threat model.
I'm already unhappy with the need for storage.googleapis.com, but
unfortunately the site doesn't work without it.
But that's probably a discussion for another time and place.
Thanks again.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Minds/front/issues/28#issuecomment-310841288>, or mute
the thread

**Comment by markharding** [comment]
Ok great. As for your other issue, lets keep that in #29.
